---
title: "Hungarian οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½οΏ½"
categories: ["Σούπες"]
---

Λιώνω 60 γρ. βούτυρο σε μεγάλη κατσαρόλα σε μέτρια φωτιά. Μόλις αρχίσει να αφρίζει, προσθέτω 1 μεγάλο κρεμμύδι ψιλοκομμένο και 450 γρ. μανιτάρια κρεμίνι κομμένα σε φέτες. Μαγειρεύω, ανακατεύοντας περιστασιακά, μέχρι να μαλακώσει το κρεμμύδι και να βγάλουν τα μανιτάρια τα υγρά τους, περίπου 8 λεπτά.

Ρίχνω 500 ml ζωμό λαχανικών ή κότας, 120 ml λευκό ξηρό κρασί, 2 κ.γ. αποξηραμένο άνηθο, 2 κ.γ. φρέσκο θυμάρι, 2 κ.γ. γλυκιά πάπρικα, 2 κ.σ. σος Worcestershire και 1 κ.γ. αλάτι. Ανεβάζω τη φωτιά στο μέγιστο μέχρι να βράσει, μετά χαμηλώνω και σιγοβράζω, ανακατεύοντας περιστασιακά, μέχρι να μειωθεί το υγρό κατά το 1/3, περίπου 10 λεπτά.

Σε ένα μικρό μπολ ανακατεύω 3 κ.σ. αλεύρι με 240 ml γάλα πλήρες μέχρι να γίνει λείο μείγμα. Το ρίχνω σιγά-σιγά στη σούπα, ανακατεύοντας συνεχώς, και συνεχίζω το μαγείρεμα μέχρι να δέσει η σούπα, περίπου 10 ακόμα λεπτά.

Αποσύρω την κατσαρόλα από τη φωτιά και προσθέτω 60 γρ. κρέμα γάλακτος (sour cream) και τον χυμό από 1 λεμόνι, ανακατεύοντας μέχρι να ενωθούν καλά.

Σερβίρω τη σούπα σε μπολ με μια κουταλιά κρέμα γάλακτος, ψιλοκομμένο μαϊντανό και φρεσκοτριμμένο πιπέρι.

Πηγή: [https://themodernproper.com/hungarian-mushroom-soup](https://themodernproper.com/hungarian-mushroom-soup)
