---
title: "Beef Stroganoff για 4 άτομα (caruso)"
categories: ["Κρέας"]
---

Σε τηγάνι, σε χαμηλή ένταση, βάζετε 15 ml ελαιόλαδο και σοτάρετε 1 μεσαίο κρεμμύδι για συνολικά περίπου 8 λεπτά, μέχρι να γίνει διάφανο. Μετά τα πρώτα λεπτά προσθέτετε και 1 σκελίδα σκόρδο πολτοποιημένη.

Στο τηγάνι προσθέτετε 15 γρ. βούτυρο και στη συνέχεια 250 γρ. μανιτάρια κομμένα σε φέτες, να μαραθούν. Στα 5 λεπτά περίπου, όταν έχουν ρουφήξει όλα τα λιπαρά, ρίχνετε 50 ml λευκό κρασί και ανακατεύετε να αρχίσουν να βγάζουν τα υγρά τους. Η διαδικασία μέχρι να μαραθούν και να φύγουν τα περισσότερα υγρά μπορεί να πάρει συνολικά μέχρι 15 λεπτά, οπότε παράλληλα προχωράτε στην προετοιμασία του φιλέτου. Όταν τα μανιτάρια είναι έτοιμα, με τρυπητή κουτάλα αφαιρείτε όλα τα στερεά στοιχεία από το τηγάνι σε ένα μπολ, ώστε να υποδεχτεί το φιλέτο το υπάρχον μίγμα βουτύρου-λαδιού.

Στεγνώνετε 500 γρ. φιλέτο μοσχαρίσιο με χαρτί κουζίνας, το κόβετε σε λωρίδες πάχους 1-1,5 εκ. και το τοποθετείτε σε ένα μπολ. Λίγο πριν το τσιγαρίσετε, ρίχνετε 20 γρ. αλεύρι Γ.Ο.Χ., αλατοπιπερώνετε και προσθέτετε μισό κ.γ. καυτερή καπνιστή πάπρικα, φροντίζοντας να καλυφθούν καλά όλες οι λωρίδες.

Ανεβάζετε την ένταση στο άδειο τηγάνι στο μέγιστο και προσθέτετε τις λωρίδες του φιλέτου χωρίς να ακουμπούν μεταξύ τους. Αφήνετε από τη μία πλευρά για 1:30 λεπτό περίπου, να κάνει κρούστα και να πάρει χρώμα, και γυρνάτε από την άλλη για να γίνει το ίδιο.

Μόλις πάρει χρώμα το φιλέτο και πριν ολοκληρωθεί το ψήσιμό του, επαναφέρετε στο τηγάνι τα μανιτάρια. Προσθέτετε 100 ml ζωμό κότας, μισό κ.γ. Worcestershire sauce και 1 κ.γ. English μουστάρδα, ανακατεύετε καλά και τέλος προσθέτετε 150 γρ. κρέμα γάλακτος 35%. Αφήνετε για 1 λεπτό περίπου, κλείνετε το μάτι και πασπαλίζετε με ψιλοκομμένο μαϊντανό. Το βήμα αυτό δεν πρέπει να πάρει συνολικά πάνω από 3 λεπτά, για να μη στεγνώσει το φιλέτο.

**Σερβίρισμα:** Σερβίρετε το στρογκανόφ αμέσως, πάνω σε παπαρδέλες, ταλιατέλες ή ρύζι.

Πηγή: [https://caruso.gr/beef-stroganoff/](https://caruso.gr/beef-stroganoff/)
