---
title: "Μπριζόλα κομμάτια με πουρέ πατάτας και σπαράγγια (για 2 άτομα)"
categories: ["Κρέας", "Αγαπημένο"]
---

Κόβω σε μικρά τετράγωνα κομμάτια μοσχαρίσια μπριζόλα (sirloin ή entrecote), 500 γρ. Προσθέτω Worcestershire sauce, αλάτι, πιπέρι και buttery steakhouse seasoning. Βάζω ελαιόλαδο στο τηγάνι και ψήνω τα κομμάτια από κάθε πλευρά για 2 λεπτά, σε μέτρια προς δυνατή φωτιά. Χαμηλώνω τη θερμοκρασία και προσθέτω το βούτυρο.

Για το βούτυρο χρειάζομαι: 2 κουταλιές σούπας βούτυρο, μισή κουταλιά σούπας μουστάρδα Dijon, chives, μαϊντανό, 2 κουταλάκια γλυκού λιωμένο σκόρδο, 1 κουταλάκι γλυκού χυμό λεμονιού και 1/4 κουταλάκι γλυκού πιπέρι καγιέν, πάπρικα, αλάτι και πιπέρι.

Αφού ανακατέψω το βούτυρο με την μπριζόλα, βγάζω το κρέας και βάζω τα σπαράγγια στο ίδιο τηγάνι. Σκεπάζω με το καπάκι για να ψηθούν πιο γρήγορα, περίπου 8 λεπτά, μέχρι να μαλακώσουν. Για τον πουρέ χρειάζομαι πατάτες, αλάτι, βούτυρο και λίγο γάλα.

Πηγή: [https://vm.tiktok.com/ZNdTut1Er/](https://vm.tiktok.com/ZNdTut1Er/)
